/* empty css                      */import{S as n}from"./assets/vendor-c0264615.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const a=document.querySelector(".white-theme-js"),l=document.querySelector(".dark-theme-js"),d=document.querySelector(".body-theme");l.addEventListener("click",()=>{l.classList.add("is-active"),a.classList.add("is-active"),d.classList.add("dark")});a.addEventListener("click",()=>{l.classList.remove("is-active"),a.classList.remove("is-active"),d.classList.remove("dark")});const p="/SP-electroniks-store-Vite/assets/slider-1-1x-0d58e141.jpg",u="/SP-electroniks-store-Vite/assets/slider-1-2x-6d4edfd3.jpg",h="/SP-electroniks-store-Vite/assets/slider-2-1x-6e6deda9.jpg",f="/SP-electroniks-store-Vite/assets/slider-2-2x-c42bd608.jpg",m="/SP-electroniks-store-Vite/assets/slider-3-1x-0bd7ee71.jpg",g="/SP-electroniks-store-Vite/assets/slider-3-2x-bb232605.jpg",S="/SP-electroniks-store-Vite/assets/slider-4-1x-c9b64956.jpg",x="/SP-electroniks-store-Vite/assets/slider-4-2x-c2fe8d90.jpg",y="/SP-electroniks-store-Vite/assets/slider-5-1x-30604060.jpg",b="/SP-electroniks-store-Vite/assets/slider-5-2x-616a3931.jpg",v=document.querySelector(".swiper-wrapper"),w=[{hash:"slider1",src1:p,pathImg:u,alt:"slider1"},{hash:"slider2",src1:h,pathImg:f,alt:"slider2"},{hash:"slider3",src1:m,pathImg:g,alt:"slider3"},{hash:"slider4",src1:S,pathImg:x,alt:"slider4"},{hash:"slider5",src1:y,pathImg:b,alt:"slider4"}],k=w.map(({src1:c,pathImg:s,alt:i,hash:r})=>`<div data-hash = "${r}"class="swiper-slide">
  <img
srcset="
  ${c} 1x,
  ${s} 2x
"
src="${s}"
alt="${i}"
class="swiper__img"
/>
</div>`);v.insertAdjacentHTML("afterbegin",k);new n(".swiper",{navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{type:"bullets",el:".swiper-pagination",clickable:!0,dynamicBullets:!0},simulateTouch:!0,touchRatio:1,touchAngle:45,hashNavigation:{watchState:!0},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},autoHeight:!0,loop:!0,autoplay:{delay:3e3,stopOnLastSlide:!1,disableOnInteraction:!1},speed:800,effect:"fade",fadeEffect:{crossFade:!0}});
//# sourceMappingURL=commonHelpers.js.map
